# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifier.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enotifier.proto\"&\n\tStatusBox\x12\n\n\x02Id\x18\x01 \x01(\x05\x12\r\n\x05Value\x18\x02 \x01(\t\"(\n\x07Status2\x12\n\n\x02Ok\x18\x01 \x01(\x08\x12\x11\n\tTimestamp\x18\x02 \x01(\x01\x32\x32\n\x08Notifier\x12&\n\x0cSetStatusBox\x12\n.StatusBox\x1a\x08.Status2\"\x00\x62\x06proto3')



_STATUSBOX = DESCRIPTOR.message_types_by_name['StatusBox']
_STATUS2 = DESCRIPTOR.message_types_by_name['Status2']
StatusBox = _reflection.GeneratedProtocolMessageType('StatusBox', (_message.Message,), {
  'DESCRIPTOR' : _STATUSBOX,
  '__module__' : 'notifier_pb2'
  # @@protoc_insertion_point(class_scope:StatusBox)
  })
_sym_db.RegisterMessage(StatusBox)

Status2 = _reflection.GeneratedProtocolMessageType('Status2', (_message.Message,), {
  'DESCRIPTOR' : _STATUS2,
  '__module__' : 'notifier_pb2'
  # @@protoc_insertion_point(class_scope:Status2)
  })
_sym_db.RegisterMessage(Status2)

_NOTIFIER = DESCRIPTOR.services_by_name['Notifier']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUSBOX._serialized_start=18
  _STATUSBOX._serialized_end=56
  _STATUS2._serialized_start=58
  _STATUS2._serialized_end=98
  _NOTIFIER._serialized_start=100
  _NOTIFIER._serialized_end=150
# @@protoc_insertion_point(module_scope)
