# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brobot.proto\"5\n\x0cMotorsThrust\x12\x11\n\tLeftMotor\x18\x01 \x01(\x05\x12\x12\n\nRightMotor\x18\x02 \x01(\x05\"@\n\x0eGimbalPosition\x12\x15\n\rVerticalAngle\x18\x01 \x01(\x05\x12\x17\n\x0fHorizontalAngle\x18\x02 \x01(\x05\"\x1b\n\nLaserState\x12\r\n\x05Power\x18\x01 \x01(\x05\"\'\n\x06Status\x12\n\n\x02Ok\x18\x01 \x01(\x08\x12\x11\n\tTimestamp\x18\x02 \x01(\x01\x32{\n\x05Robot\x12%\n\tSetThrust\x12\r.MotorsThrust\x1a\x07.Status\"\x00\x12\'\n\tSetGimbal\x12\x0f.GimbalPosition\x1a\x07.Status\"\x00\x12\"\n\x08SetLaser\x12\x0b.LaserState\x1a\x07.Status\"\x00\x62\x06proto3')



_MOTORSTHRUST = DESCRIPTOR.message_types_by_name['MotorsThrust']
_GIMBALPOSITION = DESCRIPTOR.message_types_by_name['GimbalPosition']
_LASERSTATE = DESCRIPTOR.message_types_by_name['LaserState']
_STATUS = DESCRIPTOR.message_types_by_name['Status']
MotorsThrust = _reflection.GeneratedProtocolMessageType('MotorsThrust', (_message.Message,), {
  'DESCRIPTOR' : _MOTORSTHRUST,
  '__module__' : 'robot_pb2'
  # @@protoc_insertion_point(class_scope:MotorsThrust)
  })
_sym_db.RegisterMessage(MotorsThrust)

GimbalPosition = _reflection.GeneratedProtocolMessageType('GimbalPosition', (_message.Message,), {
  'DESCRIPTOR' : _GIMBALPOSITION,
  '__module__' : 'robot_pb2'
  # @@protoc_insertion_point(class_scope:GimbalPosition)
  })
_sym_db.RegisterMessage(GimbalPosition)

LaserState = _reflection.GeneratedProtocolMessageType('LaserState', (_message.Message,), {
  'DESCRIPTOR' : _LASERSTATE,
  '__module__' : 'robot_pb2'
  # @@protoc_insertion_point(class_scope:LaserState)
  })
_sym_db.RegisterMessage(LaserState)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'robot_pb2'
  # @@protoc_insertion_point(class_scope:Status)
  })
_sym_db.RegisterMessage(Status)

_ROBOT = DESCRIPTOR.services_by_name['Robot']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MOTORSTHRUST._serialized_start=15
  _MOTORSTHRUST._serialized_end=68
  _GIMBALPOSITION._serialized_start=70
  _GIMBALPOSITION._serialized_end=134
  _LASERSTATE._serialized_start=136
  _LASERSTATE._serialized_end=163
  _STATUS._serialized_start=165
  _STATUS._serialized_end=204
  _ROBOT._serialized_start=206
  _ROBOT._serialized_end=329
# @@protoc_insertion_point(module_scope)
